ARG GO_IMAGE=golang:1.26.7-bookworm

FROM ${GO_IMAGE}

ARG AIR_VERSION=v1.65.3

WORKDIR /workspace

ENV GOTOOLCHAIN=local \
    GOMODCACHE=/go/pkg/mod \
    GOCACHE=/root/.cache/go-build

RUN go install github.com/air-verse/air@${AIR_VERSION}

CMD ["air", "-c", ".air.toml"]
